typography_spectrum: 0.026488567236810923
color:
  brandStrength: 0.5132190911099315
  lightness: 0.2577141700312495
  saturation: 0.57475735549815
  rhythmicContrast: 0.8640277297236025
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.6797607997432351
author:
  name: T&M Scroggs
  email: us@hnycmbcreative.com
  url: hnycmbcreative.com
name: with wonder
title: with wonder
description: it's how you see the world that makes the difference.
